name: speed_programming_test
description: "A horror-themed Flutter movie catalog app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/image.png
   - assets/images/bernapas.jpg
   - assets/images/friday.jpg
   - assets/images/hallowen.jpg
   - assets/images/satusuro.jpg
   - assets/images/teriffier.jpg
   - assets/images/texas.jpg
  
  
  
  
  